name: Roll Call Import
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'
      - 'bin/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'bin/*'
jobs:
  import:
    permissions:
      contents: read
      id-token: write
      actions: read

    runs-on:
      - ubuntu-20.04

    steps:
#       - name: Checkout Congress Repo
#         run: git clone https://github.com/shaun-prolegis/congress.git
# #        run: git clone https://github.com/unitedstates/congress.git

#       - name: Change directory into Congress repo
#         run: cd congress

#       - name: print working directory
#         run: pwd

#       - name: list files + directories
#         run: ls -a

#       - name: Install wget and pip
#         run: sudo apt-get install git python3-dev libxml2-dev libxslt1-dev libz-dev python3-pip python3-venv

#       - name: Create virtual environment
#         run: python3 -m venv env

#       - name: Activate environment
#         run: source env/bin/activate

#       - name: Check pip
#         run: pip --version

      
      - name: checkout repo
        uses: actions/checkout@v2.3.4
        with:
          repository: unitedstates/congress  # GitHub repository you want to checkout
          ref: main  # Change this to your desired branch
      - name: listfiles
        run: |
          ls -al
          cd congress
          ls -al
          pwd
          usc-run votes

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Change this to your desired Python version
      - name: Create Python virtual environment
        run: python -m venv venv
      - name: listfiles
        run: ls -al
      - name: Activate virtual environment
        run: source venv/bin/activate
      - name: Run usc-run
        run: /path/to/usc-run votes


      # - name: Find usc-run path
      #   run: |
      #     which usc-run
  

      - name: congcommand
        run: usc-run votes
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  
          
      - name: Run your Python script
        run: python your_script.py  # Replace with your actual Python sc
  
      - name: install
        run: |
          ls -al
          sudo apt-get install git python3-dev libxml2-dev libxslt1-dev libz-dev python3-pip python3-venv
          ls -al
      - name: testa
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install .
          usc-run votes

      - name: Collect roll call votes data
        run: |
          ls -a

      - name: Import data to S3
        run: |
          ls -al
          pwd
          python run.py votes
          # cd congress
          # python import_to_s3_script.py
